import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebarweb from "./components/Sidebarweb";
import Toprightbar from "./components/Toprightbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-00 w-full __className_82acca __variable_ea5f4b __variable_0f6017">
          <div className="lg:pl-6 xl:pl-0">
            <div className="lg:w-[1200px] w-full min-h-screen mx-auto flex font-body">
              <Sidebarweb />
              <div className="w-full lg:pl-[212px] lg:border-r border-primaryBorder">
                <Toprightbar />
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
